-- AlterTable
ALTER TABLE `Commande` MODIFY `dateCreation` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Creneau` MODIFY `dateCreation` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Panier` MODIFY `dateCreation` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Participation` MODIFY `dateCreation` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Type_Produit` MODIFY `dateCreation` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
